services:
  tailwings:
    build:
      context: .
      dockerfile: Dockerfile
    image: thinker007/tailwings:latest
    container_name: tailwings
    ports:
      - 127.0.0.1:8080:8080  # 只绑定本地
      - 0.0.0.0:3478:3478/udp  # STUN 端口
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    volumes:
      - /var/lib/tailscale/tailscaled.state:/var/lib/tailscale/tailscaled.state
      - ./etc/sysctl.conf:/etc/sysctl.conf
    restart: unless-stopped
    
