services:
  tailwings:
    build:
      context: .
      dockerfile: Dockerfile
    image: thinker007/tailwings:latest
    container_name: tailwings
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    volumes:
      - /var/lib/tailscale/tailscaled.state:/var/lib/tailscale/tailscaled.state:ro
    restart: unless-stopped
    
